version: '3.9'

services:
  backend:
    container_name: backend
    build: ./Backend
    ports:
      - "4030:4030"
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=employee_portal
      - DB_PASSWORD=admin123
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "4051:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: employee_portal
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  employee-side:
    container_name: employee-side
    build: ./Employee-side
    ports:
      - "5021:80"
    depends_on:
      - backend

  hr-view:
    container_name: hr-view
    build: ./HR-view
    ports:
      - "5022:80"
    depends_on:
      - backend

volumes:
  pgdata:

